### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by zackkatz**
- Convert to external JS file, only enqueue when a form contains a text
  field with Custom CSS Class that contains "helpscout-docs"
- search entire docs site instead of a few options
- url-encode query
- strip non-supported characters from query
- add filters to modify API key
- Set result limits and minimum characters counts

### CODE REVIEW

**Comment by zackkatz** [comment]
@pippinsplugins is there a reason you were limiting the search results to those four collection IDs? I had code working that would use collection IDs still, but I realized I should just query all the docs.

**Comment by pippinsplugins** [comment]
@zackkatz Just remembered about this.

We limited it to those collections because at the time HS did not provide a site-wide search. Looks like that's new. Awesome! Testing this out now.

**Comment by pippinsplugins** [comment]
Nvm, I remember why we limited it. We have multiple doc sites in our helpscout account. If a collection ID is not supplied, EDD search results can include AffiliateWP results, for example.

**Comment by pippinsplugins** [comment]
Unfortunately there is not a way to search multiple collections at once, so we had to do multiple queries.

Now I'm thinking it might be best to add an option to set specific collections and then just filter out the results instead of doing multiple queries.

**Pull request merged**
